image:
  file: .gitpod.dockerfile
tasks:
 - init: . ${GITPOD_REPO_ROOT}/.vscode/init_tasks.sh
 - command: . ${GITPOD_REPO_ROOT}/.vscode/analytics.sh &
   name: Startup ping
vscode:
  extensions:
    - ms-python.python
    - formulahendry.auto-close-tag
    - mkaufman.HTMLHint
    - eventyret.bootstrap-4-cdn-snippet
    - kevinglasson.cornflakes-linter
    - hookyqr.beautify
